services:
  node:
    image: node:23-alpine
    user: node
    working_dir: /home/node/${COMPOSE_PROJECT_NAME}/
    environment:
      - NODE_ENV=development
    tty: true
    volumes:
      - ./:/home/node/${COMPOSE_PROJECT_NAME}/
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
