import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import CssBaseline from "@mui/material/CssBaseline";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "@/app/theme";
import MainContainer from "@/components/server/main-container";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";

export const metadata: Metadata = {
  title: "Nova Dashboard",
  description: "Generated by create next app",
};

// eslint-disable-next-line @typescript-eslint/prefer-readonly-parameter-types
const RootLayout: FC = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <InitColorSchemeScript attribute="class" />
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <MainContainer>{children}</MainContainer>
          </ThemeProvider>
        </AppRouterCacheProvider>
        <SpeedInsights />
      </body>
    </html>
  );
};

export default RootLayout;
