import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import CssBaseline from "@mui/material/CssBaseline";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// eslint-disable-next-line @typescript-eslint/prefer-readonly-parameter-types
const RootLayout: FC = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <CssBaseline />
          {children}
        </AppRouterCacheProvider>
        <SpeedInsights />
      </body>
    </html>
  );
};

export default RootLayout;
